[2024-11-08T09:39:01.243+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-08T09:39:01.252+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: projet_groupe.push scheduled__2024-11-08T09:38:00+00:00 [queued]>
[2024-11-08T09:39:01.257+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: projet_groupe.push scheduled__2024-11-08T09:38:00+00:00 [queued]>
[2024-11-08T09:39:01.257+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-11-08T09:39:01.266+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): push> on 2024-11-08 09:38:00+00:00
[2024-11-08T09:39:01.271+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3864) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-08T09:39:01.272+0000] {standard_task_runner.py:72} INFO - Started process 3874 to run task
[2024-11-08T09:39:01.273+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'projet_groupe', 'push', 'scheduled__2024-11-08T09:38:00+00:00', '--job-id', '2696', '--raw', '--subdir', 'DAGS_FOLDER/projet.py', '--cfg-path', '/tmp/tmp6p9nsbjz']
[2024-11-08T09:39:01.273+0000] {standard_task_runner.py:105} INFO - Job 2696: Subtask push
[2024-11-08T09:39:01.303+0000] {task_command.py:467} INFO - Running <TaskInstance: projet_groupe.push scheduled__2024-11-08T09:38:00+00:00 [running]> on host 5365fe4338c6
[2024-11-08T09:39:01.342+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='projet_groupe' AIRFLOW_CTX_TASK_ID='push' AIRFLOW_CTX_EXECUTION_DATE='2024-11-08T09:38:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-08T09:38:00+00:00'
[2024-11-08T09:39:01.343+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-08T09:39:01.343+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-08T09:39:01.343+0000] {logging_mixin.py:190} INFO - Current task name:push state:running start_date:2024-11-08 09:39:01.252646+00:00
[2024-11-08T09:39:01.343+0000] {logging_mixin.py:190} INFO - Dag name:projet_groupe and current dag run status:running
[2024-11-08T09:39:01.343+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-08T09:39:01.387+0000] {logging_mixin.py:190} INFO - 200
[2024-11-08T09:39:01.387+0000] {logging_mixin.py:190} INFO - hello data
[2024-11-08T09:39:01.387+0000] {logging_mixin.py:190} INFO - [{'id': 'bitcoin', 'symbol': 'btc', 'name': 'Bitcoin', 'image': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400', 'current_price': 76096, 'market_cap': 1504318650005, 'market_cap_rank': 1, 'fully_diluted_valuation': 1597152694015, 'total_volume': 64924673968, 'high_24h': 76873, 'low_24h': 74669, 'price_change_24h': 1132.05, 'price_change_percentage_24h': 1.51011, 'market_cap_change_24h': 19635492223, 'market_cap_change_percentage_24h': 1.32254, 'circulating_supply': 19779381.0, 'total_supply': 21000000.0, 'max_supply': 21000000.0, 'ath': 76873, 'ath_change_percentage': -1.06176, 'ath_date': '2024-11-07T20:21:22.145Z', 'atl': 67.81, 'atl_change_percentage': 112062.70768, 'atl_date': '2013-07-06T00:00:00.000Z', 'roi': None, 'last_updated': '2024-11-08T09:40:58.676Z'}]
[2024-11-08T09:39:01.387+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/projet.py", line 46, in data_db
    parameters=(data['crypto'], data['prix'], data['max_prix_24h'], data['min_prix_24h'], data['date'])
                ~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
[2024-11-08T09:39:01.392+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-08T09:39:01.393+0000] {logging_mixin.py:190} INFO - Task start:2024-11-08 09:39:01.252646+00:00 end:2024-11-08 09:39:01.392648+00:00 duration:0.140002
[2024-11-08T09:39:01.393+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): push> dag:<DAG: projet_groupe> dagrun:<DagRun projet_groupe @ 2024-11-08 09:38:00+00:00: scheduled__2024-11-08T09:38:00+00:00, state:running, queued_at: 2024-11-08 09:39:00.545333+00:00. externally triggered: False>
[2024-11-08T09:39:01.393+0000] {logging_mixin.py:190} INFO - Failure caused by list indices must be integers or slices, not str
[2024-11-08T09:39:01.393+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=projet_groupe, task_id=push, run_id=scheduled__2024-11-08T09:38:00+00:00, execution_date=20241108T093800, start_date=20241108T093901, end_date=20241108T093901
[2024-11-08T09:39:01.400+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-08T09:39:01.400+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 2696 for task push (list indices must be integers or slices, not str; 3874)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/projet.py", line 46, in data_db
    parameters=(data['crypto'], data['prix'], data['max_prix_24h'], data['min_prix_24h'], data['date'])
                ~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
[2024-11-08T09:39:01.445+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-08T09:39:01.454+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-08T09:39:01.455+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
